### ISSUE TITLE
Github API key is not setting up

### ISSUE THREAD

**Issue by mharis111** [KnowledgeCaptureAndDiscovery/somef#540]
Hi,
I am trying to setup the GitHub API key in somef, but it is not working. Although it shows the success when the token setup is finished. When I execute the code, it just shows the default limit (60 calls). Any hints about the issue, or it could be due to any installation problem? I installed somef with the python package and Github repository but still facing the issue.

Is there any alternate way I can set up API key manually in the configuration file of some?
Thank you for your help.

**Comment by dgarijo** [comment]
Hi,
It does not look like an installation problem, because that's a simple request. If you install form source, in https://github.com/KnowledgeCaptureAndDiscovery/somef/pull/541 I added logging to see where the config file is saved. Usually this is at `~/.somef/config.json`. You can edit this file manually.

I re-tested this (as it's the default configuration I use) and I everything seems to work fine with my token. Please consider that if there is a problem with your token, you get the 60 calls by default. I use my personal GitHub token (the one I use for commits and so on). Do you see any errors?

Other workarounds: 
- If you really want to test whether the token works, install from source, and in `process_repository.py` in line 316 change `file_paths[constants.CONF_AUTHORIZATION]` with your token id.
- Alternatively, you can run somef without calls for the GitHub API (although some important information is lost)

I am testing this in Python 3.10. But This is one of the few things that have not changed since the beginning of the project.

**Comment by dgarijo** [comment]
No problem!
